name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 4" # every Thursday

permissions:
  contents: read

jobs:
  call-dev-support-test:
    uses: solidusio/solidus_dev_support/.github/workflows/test.yml@reusable-workflows
